### ISSUE TITLE
Tried implementing changes

### ISSUE THREAD

**Issue by INTONIGHT** [INTONIGHT/SeniorCapstone#2]
Tried implemengint the changes and it did open it up on an http server but on trying to open up the home.html page and clicking create spreadhseed nothing occured.

**Comment by cougswin1** [comment]
Ive been through the Home.HTML and then reviewed Erics notes from before. Eric says that he was able to get it running after adding the Request.send() portion. This leads me to believe that there is a simple syntax issue preventing home.js from reading correctly. Study over your code and see where maybe you left off a ; or other minor detail that might have affected the execution of the function.

**Comment by INTONIGHT** [comment]
Changes worked now to make it actually display correctly
